name: $(BuildID)

trigger: none
#   - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: secrets

stages:
- stage: Terraform
  displayName: Terraform
  jobs:
  - template: terraform.yaml

