jobs:
- job: Terraform
  displayName: Terraform

  steps:
  - bash: |
      echo "tf-state-resource-group: ${tf-state-resource-group:0:1} ${tf-state-resource-group:0:100}"
      echo "tf-state-storage-account: ${tf-state-storage-account:0:1} ${tf-state-storage-account:0:100}"
      echo "tf-state-container: ${tf-state-container:0:1} ${tf-state-container:0:100}"
      echo "tf-state-key: ${tf-state-key:0:1} ${tf-state-key:0:100}"
      echo "ARM-ACCESS-KEY: ${ARM-ACCESS-KEY:0:1} ${ARM-ACCESS-KEY:0:100}"
      echo "ARM-CLIENT-ID: ${ARM-CLIENT-ID:0:1} ${ARM-CLIENT-ID:0:100}"
      echo "ARM-CLIENT-SECRET: ${ARM-CLIENT-SECRET:0:1} ${ARM-CLIENT-SECRET:0:100}"
      echo "ARM-SUBSCRIPTION-ID: ${ARM-SUBSCRIPTION-ID:0:1} ${ARM-SUBSCRIPTION-ID:0:100}"
      echo "ARM-TENANT-ID: ${ARM-TENANT-ID:0:1} ${ARM-TENANT-ID:0:100}"
    displayName: Print variables

  - checkout: self
    displayName: Checkout repository

  - bash: |
      sudo apt-get install wget unzip -y
      wget https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
      unzip -o terraform*.zip
      sudo mv terraform /usr/local/bin/
      terraform --version
    displayName: Install Terraform

  - bash: |
      terraform init \
        -backend-config="resource_group_name=$(tf-state-resource-group)" \
        -backend-config="storage_account_name=$(tf-state-storage-account)" \
        -backend-config="container_name=$(tf-state-container)" \
        -backend-config="key=$(tf-state-key)"
    displayName: Terraform Init
    workingDirectory: $(System.DefaultWorkingDirectory)/devops/terraform
    env:
      ARM_ACCESS_KEY: $(ARM-ACCESS-KEY)
      ARM_CLIENT_ID: $(ARM-CLIENT-ID)
      ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)
      ARM_TENANT_ID: $(ARM-TENANT-ID)

  - bash: |
      terraform plan -input=false
    displayName: Terraform Plan
    workingDirectory: $(System.DefaultWorkingDirectory)/devops/terraform
    env:
      ARM_ACCESS_KEY: $(ARM-ACCESS-KEY)
      ARM_CLIENT_ID: $(ARM-CLIENT-ID)
      ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)
      ARM_TENANT_ID: $(ARM-TENANT-ID)

  - bash: |
      terraform apply -input=false -auto-approve
    displayName: Terraform Apply
    workingDirectory: $(System.DefaultWorkingDirectory)/devops/terraform
    env:
      ARM_ACCESS_KEY: $(ARM-ACCESS-KEY)
      ARM_CLIENT_ID: $(ARM-CLIENT-ID)
      ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)
      ARM_TENANT_ID: $(ARM-TENANT-ID)

